[package]
name = "deno_installer"
version = "0.1.1"
edition = "2021"

[lib]
name = "deno_installer"
crate-type = ["cdylib"]

[dependencies]
tauri-bundler = "1.0.0-rc.9"
deno_bindgen = "0.5.1"
serde = "1.0.137"